language: "en_us"

# Set the delay between votes in seconds
# 0: disabled
# Default: 300
vote_delay: 300

# Mandatory = Open the vote menu when a vote happens and don't allow closing it
# Default: true
mandatory: true

# Optional = Open the vote menu when `/vote` is executed, allow to close it
# Don't open the vote menu if enabled, mandatory is ignored if set to True
optional: false

# Disabled votes
# Use id (id = name in lowercase, replace space with underscore)
# Default: []
disabled_votes: []