language: "en_us"

# Set the delay between votes in seconds
# 0: disabled
# Default: 300
vote_delay: 300

# Is voting mandatory ?
# Default: true
mandatory: true

# Optional
# Don't open the vote menu if enabled, mandatory is ignored if set to True
optional: false

# Disabled votes
# Use id (id = name in lowercase, replace space with underscore)
# Default: []
disabled_votes: []