[book]
authors = ["MathiasDPX"]
language = "en"
multilingual = false
src = "src"
title = "Vote Update's Wiki"

[output.html]
git-repository-url = "https://github.com/MathiasDPX/VoteUpdate"
edit-url-template = "https://github.com/MathiasDPX/VoteUpdate/tree/master/wiki/{path}"
site-url = "/VoteUpdate/"